on:
  push:
    branches: [ "master" ]

env:
  NEXUS_REGISTRY: registry-new.devnerd.store # nexus repo for storing docker image 
  IMAGE_NAME: reactjs-image-nexus
  TAG: "v0.1.0" # version dynamic 
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest 
    environment: NEXUS_REPOSITORY
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3


    # - name: Use with SHA 
    #   run: echo "TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV
    - name: Login to Nexus Registry
      run: |
        echo "${{ secrets.PASSWORD }}" | docker login ${{ env.NEXUS_REGISTRY }} -u ${{ secrets.USERNAME }} --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ env.NEXUS_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} .
 

    - name: Push Docker image
      run: |
        docker push ${{ env.NEXUS_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}

    - name: Logout from Nexus Registry 
      if: always() # this ensure the logout runs even if the previous step fails. 
      run: |
        docker logout ${{ env.NEXUS_REGISTRY }}