# naming of the file should be 


# Note: thsi is regular docker build without  using the docker builderx for different platform 
# .github/workflows/docker-build.yaml
name: React Docker Build and Push

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "main" ]

env:
  NEXUS_REGISTRY: your-nexus-registry-url:8083
  NEXUS_REPOSITORY: docker-hosted
  IMAGE_NAME: react-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest 
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Checking the secret values 
      run: | 
        echo "${{ secrets.NEXUS_REGISTRY.USERNAME}}"
        echo "This is another value ${{  secrets.PASSWORD }}"
    # - name: Use with SHA 
    #   run: echo "TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV
    # - name: Login to Nexus Registry
    #   run: |
    #     echo "${{ secrets.NEXUS_PASSWORD }}" | docker login ${{ env.NEXUS_REGISTRY }} -u ${{ secrets.NEXUS_USERNAME }} --password-stdin

    # - name: Build Docker image
    #   run: docker build -t ${{ env.NEXUS_REGISTRY }}/${{ env.NEXUS_REPOSITORY }}/${{ env.IMAGE_NAME }}:latest .
    #   # run: |
    #   #   docker build -t ${{ env.NEXUS_REGISTRY }}/${{ env.NEXUS_REPOSITORY }}/${{ env.IMAGE_NAME }}:latest \
    #   #               -t ${{ env.NEXUS_REGISTRY }}/${{ env.NEXUS_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.BUILD_ID }} .

    # - name: Push Docker image
    #   run: |
    #     docker push ${{ env.NEXUS_REGISTRY }}/${{ env.NEXUS_REPOSITORY }}/${{ env.IMAGE_NAME }}:latest
    #     docker push ${{ env.NEXUS_REGISTRY }}/${{ env.NEXUS_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.BUILD_ID }}
    # - name: Logout from Nexus Registry 
    #   if: always() # this ensure the logout runs even if the previous step fails. 
    #   run: |
    #     docker logout ${{ env.NEXUS_REGISTRY }}